import Layout from "@/components/Layout";

import "./globals.css";

export const metadata = {
  title: "Audio NFT Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Layout>
      <html lang="en">
        <body>{children}</body>
      </html>
    </Layout>
  );
}
